package com.ks.db.hibernate;
// Generated 31-Oct-2017 16:07:26 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FacebookPlace generated by hbm2java
 */
@Entity
@Table(name = "facebook_place", catalog = "pr")
public class FacebookPlace implements java.io.Serializable {

	private Integer id;
	private String facebookId;
	private String facebookName;
	private String facebookUrl;
	private String facebookDescription;
	private Boolean hasEvents;
	private Integer rate;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private Boolean isDeleted;
	private boolean autoFilterEvents;
	private boolean manuallyAdded;
	
	public FacebookPlace() {
	}

	public FacebookPlace(String facebookUrl) {
		this.facebookUrl = facebookUrl;
	}

	public FacebookPlace(String facebookId, String facebookName, String facebookUrl, String facebookDescription,
			Boolean hasEvents, Integer rate, BigDecimal latitude, BigDecimal longitude, Boolean isDeleted) {
		this.facebookId = facebookId;
		this.facebookName = facebookName;
		this.facebookUrl = facebookUrl;
		this.facebookDescription = facebookDescription;
		this.hasEvents = hasEvents;
		this.rate = rate;
		this.latitude = latitude;
		this.longitude = longitude;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "facebook_id", length = 500)
	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	@Column(name = "facebook_name", length = 65535)
	public String getFacebookName() {
		return this.facebookName;
	}

	public void setFacebookName(String facebookName) {
		this.facebookName = facebookName;
	}

	@Column(name = "facebook_url", nullable = true, length = 65535)
	public String getFacebookUrl() {
		return this.facebookUrl;
	}

	public void setFacebookUrl(String facebookUrl) {
		this.facebookUrl = facebookUrl;
	}

	@Column(name = "facebook_description", length = 65535)
	public String getFacebookDescription() {
		return this.facebookDescription;
	}

	public void setFacebookDescription(String facebookDescription) {
		this.facebookDescription = facebookDescription;
	}

	@Column(name = "has_events")
	public Boolean getHasEvents() {
		return this.hasEvents;
	}

	public void setHasEvents(Boolean hasEvents) {
		this.hasEvents = hasEvents;
	}

	@Column(name = "rate")
	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	@Column(name = "latitude", precision = 20, scale = 10)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 20, scale = 10)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "auto_filter_events", nullable = false)
	public boolean isAutoFilterEvents() {
		return this.autoFilterEvents;
	}

	public void setAutoFilterEvents(boolean autoFilterEvents) {
		this.autoFilterEvents = autoFilterEvents;
	}
	
	@Column(name = "manually_added", nullable = false)
	public boolean isManuallyAdded() {
		return this.manuallyAdded;
	}

	public void setManuallyAdded(boolean manuallyAdded) {
		this.manuallyAdded = manuallyAdded;
	}

}
