package com.ks.db.hibernate;
// Generated 31-Oct-2017 16:07:26 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacebookPlaceSearch generated by hbm2java
 */
@Entity
@Table(name = "facebook_place_search", catalog = "pr")
public class FacebookPlaceSearch implements java.io.Serializable {

	private Integer id;
	private BigDecimal lastCenterLat;
	private BigDecimal lastCenterLong;
	private Date createdDate;
	private Date updatedDate;
	private Boolean isFinished;

	public FacebookPlaceSearch() {
	}

	public FacebookPlaceSearch(Date createdDate, Date updatedDate) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public FacebookPlaceSearch(BigDecimal lastCenterLat, BigDecimal lastCenterLong, Date createdDate, Date updatedDate,
			Boolean isFinished) {
		this.lastCenterLat = lastCenterLat;
		this.lastCenterLong = lastCenterLong;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.isFinished = isFinished;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "last_center_lat", precision = 20, scale = 10)
	public BigDecimal getLastCenterLat() {
		return this.lastCenterLat;
	}

	public void setLastCenterLat(BigDecimal lastCenterLat) {
		this.lastCenterLat = lastCenterLat;
	}

	@Column(name = "last_center_long", precision = 20, scale = 10)
	public BigDecimal getLastCenterLong() {
		return this.lastCenterLong;
	}

	public void setLastCenterLong(BigDecimal lastCenterLong) {
		this.lastCenterLong = lastCenterLong;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "is_finished")
	public Boolean getIsFinished() {
		return this.isFinished;
	}

	public void setIsFinished(Boolean isFinished) {
		this.isFinished = isFinished;
	}

}
